/*
테이블 
- DEPARTMENT  부모
- EMPLOYEE    자식(부모-DEPARTMENT)
- PROJECT     부모
- PROCEEDING  자식(부모-EMPLOYEE, PROJECT)

생성- 부모먼저
삭제- 자식먼저
*/

DROP TABLE PROCEEDING;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT(
    DEPT_NO       VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME     VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL
);

CREATE TABLE PROJECT(
    PJT_NO     NUMBER            NOT NULL,    -- NUMBER는 크기가 없을 수 있는데, VARCHAR2나 CHAR는 크기를 반드시 지정해주어야 한다.
    PJT_NAME   VARCHAR2(30 BYTE) NULL,
    BEGIN_DATE DATE              NULL,
    END_DATE   DATE              NULL
);

CREATE TABLE EMPLOYEE(
    EMP_NO    NUMBER            NOT NULL,
    DEPT_NO   VARCHAR2(15 BYTE) NULL,
    POSITION  CHAR(10 BYTE)     NULL,
    NAME      VARCHAR2(15 BYTE) NULL,
    HIRE_DATE DATE              NULL,
    SALARY    NUMBER            NULL
);

CREATE TABLE PROCEEDING(
    PCD_NO    NUMBER NOT NULL,
    EMP_NO    NUMBER NOT NULL,
    PJT_NO    NUMBER NOT NULL,
    PJT_STATE NUMBER NOT NULL
);

-- ALTER TABLE : 테이블 수정하기 -- ALTER TABLE 역시 TABLE이 생성되어 있어야 작동

-- 기본키 추가
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO);
ALTER TABLE PROJECT 
    ADD CONSTRAINT PK_PROJECT PRIMARY KEY(PJT_NO);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT PK_PROCEEDING PRIMARY KEY(PCD_NO);

-- 외래키 추가
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPT_NO) 
    REFERENCES DEPARTMENT(DEPT_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_EMPLOYEE FOREIGN KEY(EMP_NO) 
    REFERENCES EMPLOYEE(EMP_NO);
ALTER TABLE PROCEEDING    
    ADD CONSTRAINT FK_PROCEEDING_PROJECT FOREIGN KEY(PJT_NO) 
    REFERENCES PROJECT(PJT_NO);

/*
-- 기본키/외래키 제거
-- FK에 의해서 참조되고 있는 PK는 제거할 수 없음.
-- FK를 먼저 제거해야 함.
     즉, 테이블 삭제 순서와 마찬가지로 자식 테이블의 외래키 먼저 지워야 한다
ALTER TABLE DEPARTMENT
    DROP CONSTRAINT PK_DEPARTMENT;
 -> DEPARTMENT의 PK를 지우려면 DEPARTMENT를 참고하고 있는 EMPLOYEE의 FK부터 DROP 해야 부서의 PK를 DROP 할 수 있다.

ALTER TABLE DEPARTMENT DROP PRIMARY KEY;  -- 제약조건의 이름이 없을 때 지우는 방법
*/

-- 외래키 제거 : 외래키는 2개 이상 존재할 수 있기 때문에 기본키처럼 FOREIGN KEY;로만 삭제할 수 없다
-- DEPARTMENT 테이블의 DEPT_NO 칼럼을 참조하는 외래키 제약조건을 제거해야
-- DEPARTMENT 테이블의 DEPT_NO 칼럼에 추가된 기본키 제약조건을 제거할 수 있음
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT;

    
-- 기본키 제거 방법
ALTER TABLE DEPARTMENT
    DROP CONSTRAINT PK_DEPARTMENT; 
-- ALTER TABLE DEPARTMNET
--    DROP PRIMARY KEY;     -> 기본키는 테이블 당 하나만 존재하기 때문에 PRIMARY KEY; 로도 삭제가 가능한것









