-- 계층형(Hierarchical) 게시판

-- 삭제기능이 UPDATE로 처리

DROP TABLE ACCESS_LOG;
DROP TABLE USERS;
DROP TABLE RETIRE_USERS;
DROP TABLE SLEEP_USERS;

-- 회원 테이블
CREATE TABLE USERS
(
    USER_NO NUMBER NOT NULL,
    ID VARCHAR2(45 BYTE) NOT NULL UNIQUE,
    PW VARCHAR2(64 BYTE) NOT NULL,  -- 암호화된 비번 최대 64바이트.
    NAME VARCHAR2(50 BYTE) NOT NULL,
    GENDER VARCHAR2(2 BYTE) NOT NULL,  -- M, F, NO
    EMAIL VARCHAR2(50 BYTE) NOT NULL UNIQUE,  -- 이메일 인증 때문에 UNIQUE
    MOBILE VARCHAR2(11 BYTE) NOT NULL,  -- 휴대전화번호(하이픈 제외 최대 11자리)
    BIRTHYEAR VARCHAR2(4 BYTE) NOT NULL,  -- 출생년도(YYYY)
    BIRTHDAY VARCHAR2(4 BYTE) NOT NULL,  -- 생일(MMDD)
    POSTCODE VARCHAR2(5 BYTE),  -- 우편번호
    ROAD_ADDRESS VARCHAR2(100 BYTE),  -- 도로명주소
    JIBUN_ADDRESS VARCHAR2(100 BYTE),  -- 지번주소
    DETAIL_ADDRESS VARCHAR2(100 BYTE),  -- 상세주소
    EXTRA_ADDRESS VARCHAR2(100 BYTE),  -- 참고항목
    AGREE_CODE NUMBER NOT NULL,  -- 동의여부(0:필수, 1:필수+위치, 2:필수+프로모션, 3:필수+위치+프로모션)
    SNS_TYPE VARCHAR2(10 BYTE),  -- 간편가입종류(사이트가입:null, 네아로:naver)
    JOIN_DATE DATE NOT NULL,  -- 가입일
    PW_MODIFY_DATE DATE,    -- 비번 수정일
    INFO_MODIFY_DATE DATE,  -- 회원정보 수정일
    SESSION_ID VARCHAR2(32 BYTE),  -- 세션 아이디
    SESSION_LIMIT_DATE DATE  -- 세션 만료일
);

-- 회원접속기록 (최근 접속 기록 1개만 유지)
CREATE TABLE ACCESS_LOG
(
    ACCESS_LOG_NO NUMBER NOT NULL,
    ID VARCHAR2(45 BYTE) NOT NULL UNIQUE,
    LAST_LOGIN_DATE DATE NOT NULL  -- 마지막 로그인일(로그인 한 날짜 찍히게)
);

-- USERS 기본키
ALTER TABLE USERS
    ADD CONSTRAINT USERS_PK
        PRIMARY KEY(USER_NO);
-- ACCESS_LOG 기본키
ALTER TABLE ACCESS_LOG
    ADD CONSTRAINT ACCESS_LOG_PK
        PRIMARY KEY(ACCESS_LOG_NO);
-- ACCESS_LOG 외래키
ALTER TABLE ACCESS_LOG
    ADD CONSTRAINT ACCESS_LOG_USERS_FK -- 유저의 접속 기록(유저가 아닌 사람은 access_log에 들어올 수 없음
        FOREIGN KEY(ID) REFERENCES USERS(ID)  -- USERS의 unique칼럼(ID)을 참조하는 ACCESS_LOG의 ID
            ON DELETE CASCADE;	-- 회원탈퇴하면 회원정보 전부 삭제(유저 지울 때 접속로그도 다 지우기)
-- 시퀀스
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE ACCESS_LOG_SEQ;
CREATE SEQUENCE USERS_SEQ NOCACHE;
CREATE SEQUENCE ACCESS_LOG_SEQ NOCACHE;

-- 탈퇴 테이블(※ 삭제된 아이디로 재가입하거나 탈퇴한 아이디를 복구하는 것은 불가능)
CREATE TABLE RETIRE_USERS
(
    USER_NO NUMBER NOT NULL,
    ID VARCHAR2(45 BYTE) NOT NULL UNIQUE,
    JOIN_DATE DATE,  -- 가입일
    RETIRE_DATE DATE  -- 탈퇴일
);

-- 휴면 테이블
CREATE TABLE SLEEP_USERS
(
    USER_NO NUMBER NOT NULL,
    ID VARCHAR2(45 BYTE) NOT NULL UNIQUE,
    PW VARCHAR2(64 BYTE) NOT NULL,  -- 암호화된 비번 최대 64바이트.
    NAME VARCHAR2(50 BYTE) NOT NULL,
    GENDER VARCHAR2(2 BYTE) NOT NULL,  -- M, F, NO
    EMAIL VARCHAR2(50 BYTE) NOT NULL UNIQUE,  -- 이메일 인증 때문에 UNIQUE
    MOBILE VARCHAR2(11 BYTE) NOT NULL,  -- 휴대전화번호(하이픈 제외 최대 11자리)
    BIRTHYEAR VARCHAR2(4 BYTE) NOT NULL,  -- 출생년도(YYYY)
    BIRTHDAY VARCHAR2(4 BYTE) NOT NULL,  -- 생일(MMDD)
    POSTCODE VARCHAR2(5 BYTE),  -- 우편번호
    ROAD_ADDRESS VARCHAR2(100 BYTE),  -- 도로명주소
    JIBUN_ADDRESS VARCHAR2(100 BYTE),  -- 지번주소
    DETAIL_ADDRESS VARCHAR2(100 BYTE),  -- 상세주소
    EXTRA_ADDRESS VARCHAR2(100 BYTE),  -- 참고항목
    AGREE_CODE NUMBER NOT NULL,  -- 동의여부(0:필수, 1:필수+위치, 2:필수+프로모션, 3:필수+위치+프로모션)
    SNS_TYPE VARCHAR2(10 BYTE),  -- 간편가입종류(사이트가입:null, 네아로:naver)
    JOIN_DATE DATE,  -- 가입일
    LAST_LOGIN_DATE DATE,  -- 마지막 로그인일
    SLEEP_DATE DATE  -- 휴면처리일
);



-- 계층형(Hierarchical) 게시판

DROP SEQUENCE BORAD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD (
    BOARD_NO NUMBER NOT NULL,
    MEMBERS VARCHAR2(64 BYTE) NOT NULL,
    ID VARCHAR2(32 BYTE) NOT NULL,
    TITLE  VARCHAR2(1000 BYTE) NOT NULL,
    IP     VARCHAR2(30 BYTE) NOT NULL,
    CREATE_DATE DATE NOT NULL,
    STATE  NUMBER(1) NOT NULL,  /* 정상:1, 삭제:0 */
    DEPTH  NUMBER(2) NOT NULL,  /* 원글:0, 1차댓글:1, 2차댓글:2, ... */
    GROUP_NO NUMBER NOT NULL,  /* 원글과 모든 댓글은 같은 GROUP_NO, 원글:BBS_NO, 댓글:원글의 BBS_NO */
    GROUP_ORDER NUMBER NOT NULL,  /* 동일 그룹 내 표시 순서 */
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)   
);

ALTER TABLE BOARD
    ADD CONSTRAINT BOARD_ID_FK -- 유저의 접속 기록(유저가 아닌 사람은 access_log에 들어올 수 없음
        FOREIGN KEY(ID) REFERENCES MEMBERS(ID)  -- USERS의 unique칼럼(ID)을 참조하는 ACCESS_LOG의 ID
            ON DELETE CASCADE;