DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ START WITH 100;

DROP TABLE BOARD;
CREATE TABLE BOARD(
    NO NUMBER NOT NULL,
    WRITER VARCHAR2(16 BYTE) NOT NULL,
    IP VARCHAR2(50 BYTE) NOT NULL,
    HIT NUMBER,
    CREATEDATE DATE NOT NULL,
    MODIFYDATE DATE NOT NULL,
    TITLE VARCHAR2(200 BYTE) NOT NULL,
    CONTENT VARCHAR2(700 BYTE) NOT NULL,
    CONSTRAINT PK_BOARD PRIMARY KEY(NO)
);
