DROP SEQUENCE POST_SEQ;
CREATE SEQUENCE POST_SEQ START WITH 100 NOCACHE;

DROP TABLE POST;
CREATE TABLE POST(
	POST_NO NUMBER NOT NULL,
	WRITER VARCHAR2(16 BYTE) NOT NULL,
	TITLE VARCHAR2(30 BYTE) NOT NULL,
	CONTENT VARCHAR2(500 BYTE) NOT NULL,
	CRE_DATE DATE,
	CONSTRAINT PK_POST PRIMARY KEY(POST_NO)
);


	